version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

      - name: customer_name
        tests:
          - not_null

      - name: signup_date
        tests:
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null

      - name: order_date
        tests:
          - not_null

      - name: amount
        tests:
          - not_null

      - name: status
        tests:
          - not_null